// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1sBwTvhl2eOdO8WXLObVX6imEBwGjD0',
    appId: '1:365434160477:android:103ff821763b6f3dc9d4b4',
    messagingSenderId: '365434160477',
    projectId: 'gcp-hackathon-22-5',
    databaseURL: 'https://gcp-hackathon-22-5-default-rtdb.firebaseio.com',
    storageBucket: 'gcp-hackathon-22-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAFZfdIyCyCAXJLrNumlBunVG0DsJkdQ',
    appId: '1:365434160477:ios:ed9c9e031e4e9506c9d4b4',
    messagingSenderId: '365434160477',
    projectId: 'gcp-hackathon-22-5',
    databaseURL: 'https://gcp-hackathon-22-5-default-rtdb.firebaseio.com',
    storageBucket: 'gcp-hackathon-22-5.appspot.com',
    iosClientId: '365434160477-nuu8mddkrkbrpqkuokllh4bjr38vs4ta.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneApp',
  );
}
